version: "3.3"

services:
  db:
    image: mysql:8.0.22
    container_name: db
    volumes:
      - db_data:/var/lib/mysql
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_DATABASE=wordpress
    command: "--default-authentication-plugin=mysql_native_password"
    networks:
      - app-network
    ports:
      - "3306:3306"

  wordpress:
    depends_on:
      - db
    image: wordpress:5.1.1
    container_name: wordpress
    ports:
      - "8000:80"
    restart: unless-stopped
    env_file: .env
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=$MYSQL_USER
      - WORDPRESS_DB_PASSWORD=$MYSQL_PASSWORD
      - WORDPRESS_DB_NAME=wordpress
    volumes: ["./app:/var/www/html"]
    networks:
      - app-network

volumes:
  db_data: {}

networks:
  app-network:
    driver: bridge
